name: Build and Release Electron App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Add permissions block at the workflow level
permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: arm64
          - os: macos-latest
            arch: x64
          - os: windows-latest
            arch: x64
          - os: ubuntu-latest
            arch: x64
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install Linux Dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y rpm
    
    - name: Get current date
      id: date
      run: |
        if [ "$RUNNER_OS" == "macOS" ]; then
          echo "VERSION=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
        else
          echo "VERSION=$(Get-Date -Format "yyyy.MM.dd")" >> $env:GITHUB_ENV
        fi
      shell: bash
    
    - name: Install dependencies
      run: npm ci
      
    - name: Build Electron app
      run: npm run build
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ELECTRON_BUILDER_MAINTAINER: "maintainer@example.com"
        ELECTRON_BUILDER_AUTHOR_EMAIL: "author@example.com"
        ARCH: ${{ matrix.arch }}
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}-build
        path: |
          dist/*.dmg
          dist/*.exe
          dist/*.zip
          dist/*.AppImage
          dist/*.deb
          dist/*.rpm
        if-no-files-found: ignore

  create-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Get current date
      id: date
      run: echo "VERSION=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Prepare Release Files
      run: |
        # Clean up any existing release-files directory
        rm -rf release-files
        mkdir release-files
        
        # Create a temporary directory for processing
        mkdir -p temp_files
        
        # First, collect all files and rename them consistently
        for file in **/*.dmg **/*.exe **/*.zip **/*.AppImage **/*.deb **/*.rpm; do
          if [ -f "$file" ]; then
            filename=$(basename "$file")
            dirname=$(dirname "$file")
            arch=$(echo "$dirname" | grep -o 'arm64\|x64')
            
            # Strip any existing architecture suffixes first
            basename="${filename%.*}"
            basename="${basename%-arm64}"
            basename="${basename%-x64}"
            basename="${basename%-mac-arm64}"
            basename="${basename%-mac-x64}"
            basename="${basename%-amd64}"
            basename="${basename%-x86_64}"
            basename="${basename% Setup}"
            
            ext="${filename##*.}"
            
            # Create consistent naming pattern
            case "$ext" in
              "dmg"|"zip"|"AppImage")
                newname="${basename}-${arch}.${ext}"
                ;;
              "exe")
                if [[ $filename == *"Setup"* ]]; then
                  newname="${basename} Setup-${arch}.${ext}"
                else
                  newname="${basename}-${arch}.${ext}"
                fi
                ;;
              "deb")
                newname="${basename}_amd64.${ext}"
                ;;
              "rpm")
                newname="${basename}.x86_64.${ext}"
                ;;
            esac
            
            # Move to temp directory with unique name
            cp "$file" "temp_files/${dirname//\//_}_${newname}"
          fi
        done
        
        # Move unique files to final location
        for file in temp_files/*; do
          if [ -f "$file" ]; then
            finalname=$(basename "$file" | cut -d'_' -f2-)
            cp "$file" "release-files/$finalname"
          fi
        done
        
        # Clean up temp directory
        rm -rf temp_files
        
        # List final files
        echo "Final release files:"
        ls -la release-files/
    
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.VERSION }}
        name: Release v${{ env.VERSION }}
        draft: false
        prerelease: false
        files: release-files/*
        body: |
          Automated release for version ${{ env.VERSION }}
          
          This release was automatically generated on $(date +'%Y-%m-%d %H:%M:%S')
          
          ### Changes in this release:
          - Automated build from main branch
          - Version based on date: ${{ env.VERSION }}
          
          ### Available Downloads:
          #### macOS
          - Apple Silicon (ARM64): `Arbiter Signer-arm64.dmg`, `Arbiter Signer-arm64.zip`
          - Intel (x64): `Arbiter Signer-x64.dmg`, `Arbiter Signer-x64.zip`
          
          #### Windows
          - Intel/AMD (x64): `Arbiter Signer Setup-x64.exe`, `Arbiter Signer-x64.exe`
          
          #### Linux
          - x64: `Arbiter Signer-x64.AppImage`, `arbiter-signer_amd64.deb`, `arbiter-signer.x86_64.rpm`
