name: Build and Release Electron App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Add permissions block at the workflow level
permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: arm64
          - os: macos-latest
            arch: x64
          - os: windows-latest
            arch: x64
          - os: ubuntu-latest
            arch: x64
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install Linux Dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y rpm
    
    - name: Get current date
      id: date
      run: |
        if [ "$RUNNER_OS" == "macOS" ]; then
          echo "VERSION=$(date +'%Y.%m.%d.%H%M')" >> $GITHUB_ENV
        else
          echo "VERSION=$(Get-Date -Format "yyyy.MM.dd.HHmm")" >> $env:GITHUB_ENV
        fi
      shell: bash
    
    - name: Install dependencies
      run: npm ci
      
    - name: Build Electron app
      run: npm run build
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ELECTRON_BUILDER_MAINTAINER: "maintainer@example.com"
        ELECTRON_BUILDER_AUTHOR_EMAIL: "author@example.com"
        ARCH: ${{ matrix.arch }}
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}-build
        path: |
          dist/*.dmg
          dist/*.exe
          dist/*.zip
          dist/*.AppImage
          dist/*.deb
          dist/*.rpm
        if-no-files-found: ignore

  create-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Get current date
      id: date
      run: echo "VERSION=$(date +'%Y.%m.%d.%H%M')" >> $GITHUB_ENV
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Prepare Release Files
      run: |
        # Create platform directories
        mkdir -p release-files/{macos,windows,linux}
        
        # Debug: List all available files
        echo "Available files:"
        find . -type f
        
        # Move files to their respective platform folders
        for artifact_dir in */; do
          if [[ $artifact_dir == *"macos"* ]]; then
            mv "$artifact_dir"/*.{dmg,zip} release-files/macos/ 2>/dev/null || true
          elif [[ $artifact_dir == *"windows"* ]]; then
            mv "$artifact_dir"/*.exe release-files/windows/ 2>/dev/null || true
          elif [[ $artifact_dir == *"ubuntu"* ]]; then
            mv "$artifact_dir"/*.{AppImage,deb,rpm} release-files/linux/ 2>/dev/null || true
          fi
        done
        
        # Debug: List final structure
        echo "Final directory structure:"
        find release-files -type f
    
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.VERSION }}
        name: Release v${{ env.VERSION }}
        draft: false
        prerelease: false
        files: release-files/**/*
        body: |
          Automated release for version ${{ env.VERSION }}
          
          This release was automatically generated on $(date +'%Y-%m-%d %H:%M:%S')
          
          ### Changes in this release:
          - Automated build from main branch
          - Version: ${{ env.VERSION }}
          
          ### Available Downloads:
          Check the assets section below for all available files for your platform:
          - macOS: DMG and ZIP files
          - Windows: EXE files
          - Linux: AppImage, DEB, and RPM files
